### ISSUE TITLE
Use component output in a yaml array

### ISSUE THREAD

**Issue by mikedingjan** [mach-composer/mach-composer-cli#250]
### Is your proposal related to a problem?

Currently component output doesn't get parsed into an array as you should expect.

```yaml

sites:
  components:
      - name: component
        variables:
          this_works: ${component.name.this_works}
          some_list:
            - key: some-key
              this_doesnt_work: ${component.name.this_doesnt_work}

```

The terraform code would output the ``component.name.this_doesnt_work`` and then fails during apply.
