### ISSUE TITLE
Add support for multiple URL base-urls

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#37]
If a component is marked as `has_public_api` a Frontdoor instance or API Gateway is created using the `base_url`.

In some cases multiple endpoints might be needed, for example;
- Public APIs
- Webhooks
- Admin/Management URLs

For this you want a bit more flexibility.

**Proposal**

Replace `base_url` with endpoints:
```yaml
endpoints:
  public: api.your-domain.com
  admin: admin-api.your-domain.com
  hooks: hooks.your-domain-services.io
```

Where each endpoint will get its own API Gateway / Frontdoor instance
And instead of marking a component as `has_public_api`, explicitly pass the endpoints it needs for the implementation:

**Option A**
Component variable definition
```terraform
variable "endpoints" {
  type = map(object({
    url              = string
    api_gateway_arn  = string
    api_gateway_name = string
  }))
  default = {}
}
```

MACH configuration
```yaml
components:
  - payment
    endpoints:
      - public
      - hooks
```

OR (explicit mapping in case components might expect endpoints with a different name)

MACH configuration
```yaml
components:
  - payment
    endpoints:
      - public: public
      - webhook: hooks
```

**Option B**
More explicit Terraform variable definition so that Terraform plan fails when not all endpoints are defined in the MACH configuration

```terraform
variable "endpoint_public" {
  type = object({
    url              = string
    api_gateway_arn  = string
    api_gateway_name = string
  })
}
variable "endpoint_webhooks" {
  type = object({
    url              = string
    api_gateway_arn  = string
    api_gateway_name = string
  })
}
```
