### ISSUE TITLE
Provide more endpoint options

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#41]
_Originally from post by @pimvernooij in https://github.com/labd/mach-composer/pull/40#discussion_r530404637_

We could add more options to the endpoint configurations in order to:

- Explicitly set the DNS zone if we don't want to auto-detect it
- Set the endpoint type to have more control over the API gateway endpoint_type (defaults to `REGIONAL` now) for example

Current syntax:

```yaml
endpoints:
  public: api.mach-example.com
```

We could make it hybrid so that it accepts just a string or a configuration object like so:

```yaml
endpoints:
  public: 
     url: api.mach-example.com
     zone: mach-example.com
     type: ...
```

Related: #37
