### ISSUE TITLE
Add configuration option to enable/disable auto-creation of function app plan

### ISSUE THREAD

**Issue by tleguijt** [mach-composer/mach-composer-cli#84]
At the moment, when a component has a `azure` integration, MACH assumes it needs an app service plan.

MACH will create this and pass the `app_service_plan` variable to the component.

We need to be able to support two scenarios:

- No service plans at all (site-wide)
Could be done by just defining:
```yaml
azure:
  service_plans: null
```
- Disable/enable plans per component
Probably the most elegant solution. We can skip the option above and go for the following (in line with the `endpoints` option:
```yaml
components:
  api-component:
    source: ....
    service_plan: default
  non-function-component:
    source: ....
```

Where service_plan needs to be explicitly given in order for the component to actually receive the `app_service_plan` variable
