### ISSUE TITLE
External component library support

### ISSUE THREAD

**Issue by pimvernooij** [mach-composer/mach-composer-cli#92]
In princple, MACH composer is designed to managed multiple sites from a single YAML file.

However, there are use cases where this is not desired.

In those scenario's it is however, still desirable to use a library of shared components.

To facilitate this, we should support managing those shared components, in a separate YAML file, that can be included in the mach configuration yaml file(s).

At the same time, it should be support to include:
- A local external component.yml
- A remote (git based) external component.yml, versioned in the same way that we version components
- 'Usual' components that are included in the configuration, local and remote.

```yaml
components:
  - externalStack: git::https://github.com/labd/my-platform/component-library.yml
    version: x.y.z (or sdfsdf8)
  - externalStack: ../my-platform/component-library.yml
  - name: api-extensions
    source: git::https://github.com/your-company/api-extensions-component//terraform
    integrations: [aws, commercetools, sentry]
    version: 0dd4814
  - name: my-component
    source: ../mach-component-my-component/terraform
    integrations: ["aws", "commercetools", "sentry"]
    version: latest
    artifacts:
      service:
        filename: .serverless/my-component.zip
        script: yarn package
        workdir: ../mach-component-my-component/
```

And the `external.yml` could contain the following:

```yaml
components:
  - name: payment
    source: git::https://github.com/your-company/payment-component//terraform
    integrations: [aws, commercetools, sentry]
    endpoints:
      main: main
      internal: internal
    version: 06b3cf8
  - name: ecommerce-content
    integrations: [amplience, contentful]
    source: git::https://github.com/your-company/ecommerce-content//terraform
    version: a410ce6
  - name: my-other-component
    source: ../mach-other-component-my-component/terraform
    integrations: ["aws", "sentry"]
    version: latest
    artifacts:
      service:
        filename: .serverless/my-component.zip
        script: yarn package
        workdir: ../mach-other-component-my-component/

```
